### PR TITLE
Suppress and update error logs

### LINKED ISSUE #998: Suppress duplicate Key value error message
Timestamp already exists errors - [Detail: Key (experiment_name, interval_end_time, interval_start_time)=(11787264|345199|683cb481-8f8f-4948-9173-29f730c5c03f|btr-spm-solution-prod|deployment|app-s2m-prd, 2023-10-11 00:30:00, 2023-10-11 00:15:01) already exists. 2023-10-1815:07:41.847 ERROR [qtp88397182-34][SqlExceptionHelper.java(138)]-ERROR: duplicate key value violates unique constraint "kruize_results_20231011_pkey" - This is due to the new cost operator that now sends aggregated records through out the day for customer that have enabled it.

For the last 6 hr period of the day, Kruize will have to reject 75% of the records as these would already have been added. Kruize will for now suppress printing the “duplicate key value” error message.

### PR DESCRIPTION
**Pull request by khansaad**
This PR fixes #998

### CODE REVIEW

File: src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java [hunk 1]
```diff
@@ -58,7 +58,9 @@ public void handle(String target, Request baseRequest, HttpServletRequest reques
                 .registerTypeAdapter(Date.class, new GsonUTCDateAdapter())
                 .create();
         String gsonStr = gsonObj.toJson(new KruizeResponse(origMessage, errorCode, "", "ERROR", myList));
-        LOGGER.error(gsonStr);
+        if (errorCode != HttpServletResponse.SC_CONFLICT) {
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java:61]: Please add a comment here about what is the error being suppressed here

File: src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java [hunk 2]
```diff
@@ -58,7 +58,9 @@ public void handle(String target, Request baseRequest, HttpServletRequest reques
...
+            LOGGER.error(gsonStr);
+        }
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/exceptions/KruizeErrorHandler.java:63]: We need an `else` statement here and have this in `LOGGER.debug`

File: src/main/java/com/autotune/analyzer/services/CreateExperiment.java [hunk 3]
```diff
@@ -205,7 +204,7 @@ public void sendErrorResponse(String inputRequestPayload, HttpServletResponse re
             e.printStackTrace();
             if (null == errorMsg) errorMsg = e.getMessage();
         }
-        LOGGER.error(inputRequestPayload);
+        LOGGER.debug(inputRequestPayload);
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/services/CreateExperiment.java:207]: Comment here would be good

**Review by dinogun — APPROVED** [review]
LGTM
