### PR TITLE
 fixes the typo in percentile call

### LINKED ISSUE #697: Typo with percentile for cpu requests recommendations
The cpu requests generated by algorithm is using 0.9 percentile instead of 90th percentile.

https://github.com/kruize/autotune/blob/0c7043d8cd8dd369265e1c9f0517863c7830815b/src/main/java/com/autotune/analyzer/recommendations/GenerateRecommendation.java#L141

### PR DESCRIPTION
**Pull request by bharathappali**
Fixes #697

### CODE REVIEW

**Review by msvinaykumar — APPROVED** [review]

**Review by kusumachalasani — APPROVED** [review]
LGTM!

File: src/main/java/com/autotune/common/utils/CommonUtils.java [hunk 1]
```diff
@@ -281,8 +281,29 @@ public static Timestamp addDays(Timestamp date, int days) {
         return new Timestamp(cal.getTime().getTime());
     }
 
-    public static double percentile(double percentile, List<Double> items) {
-        Collections.sort(items);
-        return items.get((int) Math.round(percentile / 100.0 * (items.size() - 1)));
+    public static double percentile(double percentile, List<Double> values) {
```
Comment (dinogun) [inline src/main/java/com/autotune/common/utils/CommonUtils.java:284]: Not sure why is this custom implementation of percentile needed? What is wrong with the one in the Math package?

Comment (bharathappali) [reply src/main/java/com/autotune/common/utils/CommonUtils.java]: Current logic is missing interpolation
