### PR TITLE
Exclude namespace queries to fetch container metric data

### LINKED ISSUE #1308: Either container / namespace based queries to be run based on the experiment_type in local monitoring
**Describe the bug**

With the latest image `quay.io/kruize/autotune_operator:0.0.25_mvp`, both container and namespace queries are being executed while trying to generate recommendations for a container based experiment.

It is expected to run only the relevant queries to not overload the datasource while running multiple experiments.

**How to reproduce it**
Run local monitoring kruize-demos and check for pod logs after completion
`./local_monitoring_demo.sh -c openshift -i quay.io/kruize/autotune_operator:0.0.25_mvp`

**Expected behavior**
Queries related to `experiment_type : container` should be run, excluding the namespace queries 

**Relevant logs**
```
2024-09-2412:12:33.494 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28container_memory_working_set_bytes%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.541 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-avg_over_time(sum by(namespace) (container_memory_rss{namespace="default", container!='', container!='POD', pod!=''})[15m:])
2024-09-2412:12:33.541 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.542 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.591 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-min_over_time(sum by(namespace) (container_memory_rss{namespace="default", container!='', container!='POD', pod!=''})[15m:])
2024-09-2412:12:33.591 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=min_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.592 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=min_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.640 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-max_over_time(sum by(namespace) (container_memory_rss{namespace="default", container!='', container!='POD', pod!=''})[15m:])
2024-09-2412:12:33.640 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.641 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28container_memory_rss%7Bnamespace%3D%22default%22%2C+container%21%3D%27%27%2C+container%21%3D%27POD%27%2C+pod%21%3D%27%27%7D%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.702 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-avg_over_time(sum by(namespace) ((kube_pod_info{namespace="default"}))[15m:])
2024-09-2412:12:33.703 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28%28kube_pod_info%7Bnamespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.703 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28%28kube_pod_info%7Bnamespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.724 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-max_over_time(sum by(namespace) ((kube_pod_info{namespace="default"}))[15m:])
2024-09-2412:12:33.724 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28%28kube_pod_info%7Bnamespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.725 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28%28kube_pod_info%7Bnamespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.755 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-avg_over_time(sum by(namespace) ((kube_pod_status_phase{phase="Running", namespace="default"}))[15m:])
2024-09-2412:12:33.755 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28%28kube_pod_status_phase%7Bphase%3D%22Running%22%2C+namespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.756 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=avg_over_time%28sum+by%28namespace%29+%28%28kube_pod_status_phase%7Bphase%3D%22Running%22%2C+namespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.787 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-max_over_time(sum by(namespace) ((kube_pod_status_phase{phase="Running", namespace="default"}))[15m:])
2024-09-2412:12:33.787 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28%28kube_pod_status_phase%7Bphase%3D%22Running%22%2C+namespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.789 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max_over_time%28sum+by%28namespace%29+%28%28kube_pod_status_phase%7Bphase%3D%22Running%22%2C+namespace%3D%22default%22%7D%29%29%5B15m%3A%5D%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
2024-09-2412:12:33.817 INFO [qtp62343880-53][RecommendationEngine.java(2095)]-max(last_over_time(timestamp((sum by (namespace) (container_cpu_usage_seconds_total{namespace="default"})) > 0 )[15d:]))
2024-09-2412:12:33.818 INFO [qtp62343880-53][RecommendationEngine.java(2104)]-http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max%28last_over_time%28timestamp%28%28sum+by+%28namespace%29+%28container_cpu_usage_seconds_total%7Bnamespace%3D%22default%22%7D%29%29+%3E+0+%29%5B15d%3A%5D%29%29&start=1725883952&end=1727179952&step=900
2024-09-2412:12:33.819 INFO [qtp62343880-53][GenericRestApiClient.java(96)]-Executing request: GET http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/query_range?query=max%28last_over_time%28timestamp%28%28sum+by+%28namespace%29+%28container_cpu_usage_seconds_total%7Bnamespace%3D%22default%22%7D%29%29+%3E+0+%29%5B15d%3A%5D%29%29&start=1725883952&end=1727179952&step=900 HTTP/1.1
```

**Environment:**
- Kubernetes Cluster:  openshift
- Version
- OS: Fedora

**Additional context**
.

### PR DESCRIPTION
**Pull request by shreyabiradar07**
## Description

This PR filters out 

- namespace queries

- redundant `maxDate` query (already executed to fetch the interval start and end time before iterating through the list of metrics)

to fetch container metric data to generate recommendations for a `container` based experiment to run only the relevant queries and not overload the datasource while running multiple experiments.

Fixes #1308

### Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested?

Tested by running local monitoring demos on ResourceHub cluster -  `./local_monitoring_demo.sh -c openshift -i quay.io/shbirada/autotune_operator:filter-namespace-for-container-reco
`

pod logs with queries run for `tfb-server` and `tfb-database` containers - https://privatebin.corp.redhat.com/?d50352a3d066c26b#4mGGpw7q2TXbrF1pN6C7yUykuphywPSwstMez2RkKWvB

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: Openshift (ResourceHub cluster)

## Checklist :dart:

- [x] Followed coding guidelines
- [x] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information

docker image - `quay.io/shbirada/autotune_operator:filter-namespace-queries`

### CODE REVIEW

**Review by msvinaykumar — CHANGES_REQUESTED** [review]
Shekar also implemented similar filtering. Can't we create a common function and reference it statically?

Is it possible to design the metric profile with subsections to handle both namespace and container queries? In the future, we might need separate queries for different workloads, so it would be better to design the metric profile object with distinct and clear separations, rather than relying on 'startswith'.

**Comment by shreyabiradar07** [comment]
> Shekar also implemented similar filtering. Can't we create a common function and reference it statically?
> 
Added a common function for filtering metrics in both the `namespace` and `container` experiment types

File: src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java [hunk 1]
```diff
@@ -2206,5 +2206,27 @@ private void prepareIntervalResults(Map<Timestamp, IntervalResults> dataResultsM
             throw new Exception(AnalyzerErrorConstants.APIErrors.UpdateRecommendationsAPI.METRIC_EXCEPTION + e.getMessage());
         }
     }
+
+    /**
+     * Filters out maxDateQuery and namespace metrics based on the experiment type
+     * @param metricProfile  Metric profile to be used
+     * @param maxDateQuery   maxDateQuery metric to be filtered out
```
Comment (msvinaykumar) [inline src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java:2213]: why maxDateQuery required to filter ?

Comment (msvinaykumar) [reply src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java:2213]: It seems that both require maxDateQuery, so is the filter still necessary?

Comment (shreyabiradar07) [reply src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java:2213]: `maxDateQuery` for both the experiment types is already executed before iterating through the list of other metrics  to calculate `interval_start_time` and `interval_end_time` - https://github.com/kruize/autotune/blob/master/src/main/java/com/autotune/analyzer/recommendations/engine/RecommendationEngine.java#L2031

it's redundant to execute it twice with other metrics present hence filtering it out.

**Review by msvinaykumar — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
@shreyabiradar07 Any reason why we are not using `kubernetes_object` to check if it is `container` or `namespace` as it is meant for exactly this purpose?

**Comment by shreyabiradar07** [comment]
@dinogun updated the function to filter metrics based on `experiment_type` and `kubernetes_object`

**Review by dinogun — APPROVED** [review]
LGTM
