### PR TITLE
Fix the NPE issue in ListExperimentsAPI

### LINKED ISSUE #908: ListExperiments API throws java.lang.NullPointerException: Cannot invoke "java.util.HashMap.values()"
Kruize pod log contains the below exception when listExperiments is invoked:

```
2023-08-2205:29:48.797 ERROR [qtp88397182-43][ListExperiments.java(384)]-Not able to generate recommendation for expName : quarkus-resteasy-kruize-min-http-response-time-db_2 due to Cannot invoke "java.util.List.iterator()" because "kubernetesAPIObjects" is null
java.lang.NullPointerException: Cannot invoke "java.util.HashMap.values()" because the return value of "com.autotune.common.data.result.ContainerData.getMetrics()" is null
	at com.autotune.analyzer.serviceObjects.Converters$KruizeObjectConverters.convertKruizeObjectToListRecommendationSO(Converters.java:239)
	at com.autotune.analyzer.services.ListExperiments.buildRecommendationsResponse(ListExperiments.java:376)
	at com.autotune.analyzer.services.ListExperiments.buildResponseBasedOnQuery(ListExperiments.java:281)
	at com.autotune.analyzer.services.ListExperiments.doGet(ListExperiments.java:151)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Steps to recreate:

Run the remote monitoring fault tolerant test using the below commands:
-  git clone https://github.com/kruize/autotune.git
- cd autotune/tests/scripts/remote_monitoring_tests/fault_tolerant_tests
- ./remote_monitoring_fault_tolerant_tests.sh -c minikube -i kruize/autotune_operator:daily -u 5  -r /tmp/results

### PR DESCRIPTION
**Pull request by khansaad**
This PR fixes #908 

- Removed the redundant convert method
- Removed the unused post method

### CODE REVIEW

File: tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh [hunk 1]
```diff
@@ -174,7 +174,7 @@ if [ "${exit_code}" -ne 0 ]; then
 	echo "Fault tolerant test failed! Check the log for details" | tee -a ${LOG}
 	exit 1
 else
-	if [[ $(grep -i "error\|exception" ${KRUIZE_POD_LOG_BEFORE}) || $(grep -i "error\|exception" ${KRUIZE_POD_LOG_AFTER}) ]]; then
+	if [[ $(grep -i "ERROR" ${KRUIZE_POD_LOG_BEFORE}) || $(grep -i "error\|exception" ${KRUIZE_POD_LOG_AFTER}) ]]; then
```
Comment (chandrams) [inline tests/scripts/remote_monitoring_tests/fault_tolerant_tests/remote_monitoring_fault_tolerant_tests.sh:177]: @khansaad - Why has this been changed?

**Comment by chandrams** [comment]
With fault tolerant test I see such messages as shown below in the pod log, these were not seen earlier, can you check.

```
[36.236s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[36.236s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[36.237s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[36.238s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
2023-12-1807:18:36.938 WARN [qtp253011924-45][ExperimentDBService.java(99)]-Converted experimentResultData is null
2023-12-1807:18:36.939 WARN [qtp253011924-45][ExperimentDBService.java(99)]-Converted experimentResultData is null
2023-12-1807:18:36.939 WARN [qtp253011924-45][ExperimentDBService.java(99)]-Converted experimentResultData is null
2023-12-1807:18:36.939 WARN [qtp253011924-45][ExperimentDBService.java(99)]-Converted experimentResultData is null
2023-12-1807:18:36.939 WARN [qtp253011924-45][ExperimentDBService.java(99)]-Converted experimentResultData is null
```

**Review by msvinaykumar — APPROVED** [review]

**Review by chandrams — APPROVED** [review]
LGTM
