### PR TITLE
Fix the index out of bound if one of the list is empty

### LINKED ISSUE #1338: Error: Index -1 out of bounds for length 0  observed while generating recommendations
**Describe the bug**

ERROR [qtp1100399456-43][RecommendationEngine.java(299)]-Failed to create recommendation for experiment: monitor_gpu and interval_start_time: null and interval_end_time: 2024-10-09 12:27:22.0
2024-10-0912:27:31.003 ERROR [qtp1100399456-43][KruizeErrorHandler.java(71)]-{"message":"Index -1 out of bounds for length 0","httpcode":500,"documentationLink":"","status":"ERROR"}

**How to reproduce it**
On NERC cluster, create an experiment using a following json.
```
[{
  "version": "v2.0",
  "experiment_name": "monitor_gpu",
  "cluster_name": "default",
  "performance_profile": "resource-optimization-local-monitoring",
  "mode": "monitor",
  "target_cluster": "local",
  "datasource": "prometheus-1",
  "kubernetes_objects": [
    {
      "type": "statefulset",
      "name": "human-eval-benchmark",
      "namespace": "unpartitioned-namespace",
      "containers": [
        {
          "container_image_name": "kruizehub/human-eval",
          "container_name": "human-eval-benchmark"
        }
      ]
    }
  ],
  "trial_settings": {
    "measurement_duration": "15min"
  },
  "recommendation_settings": {
    "threshold": "0.1"
  }
}]
```
While generating the recommendations for that experiment using the below curl command, following error is observed.
 curl -X POST http://kruize-openshift-tuning.apps.nerc-ocp-test-2.nerc.mghpcc.org/generateRecommendations?experiment_name=monitor_gpu
 
ERROR [qtp1100399456-43][RecommendationEngine.java(299)]-Failed to create recommendation for experiment: monitor_gpu and interval_start_time: null and interval_end_time: 2024-10-09 12:27:22.0
2024-10-0912:27:31.003 ERROR [qtp1100399456-43][KruizeErrorHandler.java(71)]-{"message":"Index -1 out of bounds for length 0","httpcode":500,"documentationLink":"","status":"ERROR"}

**Expected behavior**
Recommendations should be generated without the error.

**Relevant logs**
From kruize logs 
```
ERROR [qtp1100399456-43][RecommendationEngine.java(299)]-Failed to create recommendation for experiment: monitor_gpu and interval_start_time: null and interval_end_time: 2024-10-09 12:27:22.0
2024-10-0912:27:31.003 ERROR [qtp1100399456-43][KruizeErrorHandler.java(71)]-{"message":"Index -1 out of bounds for length 0","httpcode":500,"documentationLink":"","status":"ERROR"}
```

**Environment:**
- openshift
- 4.16.0

### PR DESCRIPTION
**Pull request by bharathappali**
## Description

This PR fixes the index out of bound issue which occurs when one of the result lists (GPU core or memory) are empty.

Fixes #1338 

### Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Docs update
- [ ] Breaking change (What changes might users need to make in their application due to this PR?)
- [ ] Requires DB changes

## How has this been tested?

The scenario which causes the data unavailability is considered to re-create and test with this fix.

- [ ] New Test X
- [ ] Functional testsuite

**Test Configuration**
* Kubernetes clusters tested on: 

## Checklist :dart:

- [ ] Followed coding guidelines
- [ ] Comments added
- [ ] Dependent changes merged
- [ ] Documentation updated
- [ ] Tests added or updated

## Additional information

None

### CODE REVIEW

File: src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java [hunk 1]
```diff
@@ -577,11 +582,32 @@ public Map<AnalyzerConstants.RecommendationItem, RecommendationConfigItem> getAc
...
+        if (acceleratorCoreMaxValues.isEmpty() && acceleratorMemoryMaxValues.isEmpty())
+            return null;
+
+        double coreAverage = 0.0;
+        if (!acceleratorCoreMaxValues.isEmpty())
+            coreAverage = CommonUtils.percentile(COST_ACCELERATOR_PERCENTILE, acceleratorCoreMaxValues);
+
+        double memoryAverage = 0.0;
+        if (!acceleratorMemoryMaxValues.isEmpty())
+            memoryAverage = CommonUtils.percentile(COST_ACCELERATOR_PERCENTILE, acceleratorMemoryMaxValues);
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java:595]: Looks like redundant checks as it has already been checked in line 586. Please remove them

File: src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java [hunk 2]
```diff
@@ -436,11 +440,32 @@ public Map<AnalyzerConstants.RecommendationItem, RecommendationConfigItem> getAc
...
+        if (acceleratorCoreMaxValues.isEmpty() && acceleratorMemoryMaxValues.isEmpty())
+            return null;
+
+        double coreAverage = 0.0;
+        if (!acceleratorCoreMaxValues.isEmpty())
+            coreAverage = CommonUtils.percentile(PERFORMANCE_ACCELERATOR_PERCENTILE, acceleratorCoreMaxValues);
+
+        double memoryAverage = 0.0;
+        if (!acceleratorMemoryMaxValues.isEmpty())
+            memoryAverage = CommonUtils.percentile(PERFORMANCE_ACCELERATOR_PERCENTILE, acceleratorMemoryMaxValues);
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java:453]: Same here, remove the redundant checks

File: src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java [hunk 3]
```diff
@@ -436,11 +440,32 @@ public Map<AnalyzerConstants.RecommendationItem, RecommendationConfigItem> getAc
...
+                    "Notification needs to be added explaining we changed the core usage to 100% as it's more than 100%");
+            coreFraction = 1;
+        }
         double memoryFraction = memoryAverage / 100;
+        // TODO: Need to investigate why data is faulty
+        if (memoryFraction > 1) {
+            LOGGER.info("Data irregularity detected, " +
+                    "Notification needs to be added explaining we changed the memory usage to 100% as it's more than 100%");
+            memoryFraction = 1;
+        }
```
Comment (dinogun) [inline src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java:468]: Its not clear to me why the Averages cannot be >1?  Dont we have cases where the MIG Partitions are >1 (cores/Gi). If not, what is the fraction representing and maybe add a comment that explains this

File: src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java (hunk 1 above)
Comment (bharathappali) [reply src/main/java/com/autotune/analyzer/recommendations/model/CostBasedRecommendationModel.java:595]: Thanks for the review @dinogun . In the earlier check we `continue` if both of the lists are empty. at the time of calculating percentile we check if the respective list is not empty. So I feel we will be needing this check.

File: src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java (hunk 2 above)
Comment (bharathappali) [reply src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java:453]: Thanks for the review @dinogun . In the earlier check we `continue` if both of the lists are empty. at the time of calculating percentile we check if the respective list is not empty. So I feel we will be needing this check.

File: src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java (hunk 3 above)
Comment (bharathappali) [reply src/main/java/com/autotune/analyzer/recommendations/model/PerformanceBasedRecommendationModel.java:468]: The data we deal with is percentages and we are currently considering only one GPU per container so the usage (Avg or Max) should be `100%` and when we calculate the fraction we divide by `100` so the max we need to get is `1`. Also the `AcceleratorMetaDataService` consider the core and memory fractions needed to come up with the recommended accelerator MIG profile so if fractions exceed `1` none of the MIG configs will match it (not even the whole GPU which considers core and memory fraction as `1`) and we will get `NULL` and hence there will be no recommendation. 

So if the fractions are greater than `100` there is a higher chance that there is an anomaly in data so we mark it as `1` to give out full GPU as a recommendation.

Sure will be adding this as the comment in the code.

**Review by dinogun — APPROVED** [review]
LGTM
